---
# file: roles/vcpe/handlers/main.yml

- name: Start virtualization service
  service:
    name: libvirtd
    state: started

- name: Enable virtualization service
  service:
    name: libvirtd
    enabled: yes

- name: Start network service
  service:
    name: network
    state: started

- name: Restart network service
  service:
    name: network
    state: restarted
