---
# file: roles/sat6register/tasks/main.yml

- name: Install certificates from {{ sat6_fqdn }}
  yum:
     name: "http://{{ sat6_fqdn }}/pub/katello-ca-consumer-latest.noarch.rpm"
     validate_certs: no
     state: present

- name: Register to Satellite6 only for content
  redhat_subscription:
    state: present
    activationkey: "{{ activation_key }}"
    org_id: "{{ organization_id }}"
    autosubscribe: True
    force_register: True

- name: Install the katello-agent
  yum:
    name: katello-agent
    state: latest
  notify:
    - Start katello-agent
    - Enable katello-agent
