---
# file: roles/vcpe/vars/main.yml

interfaces_network_path: "/etc/sysconfig/network-scripts"

interface_bridge_wan: "brwan"
interface_bridge_lan: "brlan"
interfaces_ethernet_bridge_wan:
    - eth0
interfaces_ethernet_bridge_lan:
    - eth1

router_version: "vyos-1.1.7-i586-virt"
router_hostname: "{{ remote_hostname |  }}"
router_vcpu: 2
router_vram: 1
upload_directory: "/root"

preloaded: "yes"