---
# file: roles/router/vars/main.yml
#
#
ansible_connection: local

ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -q -i /etc/ansible/keys/bastion.key -W %h:%p {{ remote_username }}@{{ remote_ipv4 }} -p {{ remote_port }}"'

cli:
    host: "{{ ansible_host }}"
    username: vyos
    password: vyos
    transport: cli
    
networks:
    net:
        id: 20
        device: eth0
        inet: 0.0.0.0/24
    lan:
        id: 10
        device: eth1
        inet: 192.168.1.0/24
