---
# file: roles/hostadd/tasks/main.yml
#
# tasks to add host to tower inventory
#
- name: Add tower inventory
  tower_inventory:
    name: "{{ inventory }}"
    description: "off-net hosts inventory"
    organization: "{{ organization }}"
    variables: "---"
    state: present
    tower_verify_ssl: False
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"

- name: Add host to tower inventory
  tower_host:
    name: "{{ remote_hostname }}"
    description: "off-net host {{ remote_hostname }}"
    inventory: "{{ inventory }}"
    variables:
        ansible_host: "{{ remote_ipv4 }}"
        ansible_port: "{{ remote_port }}"
    state: present
    tower_verify_ssl: False
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"

- name: Create local private key directory
  file:
    path: "{{ ssh_key_directory }}"
    owner: 'awx'
    group: 'awx'
    mode: 'u=rwx'
    state: directory

- name: Create local private key file
  template:
    src: decoded_key.j2
    dest: "{{ ssh_key_directory }}/{{ remote_hostname }}"
    owner: 'awx'
    group: 'awx'
    mode: 'u=rw'

- name: Add host credential to tower
  tower_credential:
    name: "{{ remote_hostname }}"
    description: "off-net host {{ remote_hostname }}"
    organization: "{{ organization }}"
    username: "{{ remote_username }}"
    ssh_key_data: "{{ ssh_key_directory }}/{{ remote_hostname }}"
    state: present
    tower_verify_ssl: False
    credential_type: "{{ credential_type }}"
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"

