---
# tasks to add host to tower inventory
#
- name: Add tower inventory
  tower_inventory:
    name: "{{ inventory }}"
    description: "off-net hosts inventory"
    organization: "{{ organization }}"
    variables: "---"
    state: present
    tower_verify_ssl: False
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"

- name: Add host to tower inventory
  tower_host:
    name: "{{ remote_hostname }}"
    description: "off-net host {{ remote_hostname }}"
    inventory: "{{ inventory }}"
    variables: "---"
    state: present
    tower_verify_ssl: False
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"

- name: Create local private key directory
  file:
    path: "/tmp/75BCD15/3ADE68B1/{{ remote_hostname }}"
    state: directory

- name: Create local private key file
  template:
    src: decoded_key.j2
    dest: "/tmp/75BCD15/3ADE68B1/{{ remote_hostname }}"

- name: Add host credential to tower
  tower_credential:
    name: "{{ remote_hostname }}"
    description: "off-net host {{ remote_hostname }}"
    organization: "{{ organization }}"
    kind: ssh
    ssh_key_data: "/tmp/75BCD15/3ADE68B1/{{ remote_hostname }}"
    state: present
    tower_verify_ssl: False
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"

- name: Remove local private key directory
  file:
    path: "/tmp/75BCD15/3ADE68B1/{{ remote_hostname }}"
    state: absent

